ftp:
  host: "ftp.example.com"
  port: 21
  root_dir: "/"          # starting directory after login
  passive_mode: true

target:
  folder: "/dataset/cats"      # required. no interactive picker
  ignore_dirs:                 # optional. these prefixes are skipped when scanning "other" images
    - "/dataset/tmp"
    - "/dataset/test"

cache:
  dir: "./_ftp_cache"          # local cache for downloaded images

images:
  exts: [".jpg", ".jpeg", ".png", ".bmp", ".webp"]  # lower-case
  recursive: true
  max_per_dir: 0               # 0 = no per-directory cap

embedding:
  device: "cuda"               # "cuda" or "cpu"
  batch_size: 32
  num_workers: 0               # reserved
  topk: 10                     # avg top-K similarity vs targets

review:
  seed: 42                     # sampling RNG seed

display:
  window_name: "Similarity Review"
  default_window_wh: [900, 1600]  # [height, width]
  font_scale: 0.6
  font_thick: 1

log:
  csv_path: "./move_decisions.csv"  # original_path,new_path,similarity,decision,stage,timestamp

limits:
  max_others_to_embed: 0       # 0 = no cap
