# Device and ADB
device_serial: null          # null = default device; or set a specific serial string
adb_find_cmd: "find"         # usually 'find'; keep default unless your shell differs

# Targets under /storage/emulated/0
target_folders:              # paths relative to /storage/emulated/0, must start with '/'
  - /UserFile/Image/gl
  # - /DCIM/Camera
ignore_folder_regex:         # regex patterns that match relative folder paths starting with '/'
  - '^/Android(/.*|$)'
  # - '^/Tencent(/.*|$)'

# Local cache output
local_root: "."              # working directory on PC
adb_cache_dir: "_adb_cache"  # resized 224x224 images
emb_cache_dir: "_emb_cache"  # .npy embeddings
csv_path: "index.csv"

# Performance
pull_threads: 8              # ADB pull + resize workers
batch_size: 64               # embedding batch size
num_workers: 4               # dataloader workers for embedding stage
use_fp16: true               # half precision on CUDA
device: "cuda"               # "cuda" | "cpu" | "auto"

# Image handling
max_image_pixels: null       # null disables PIL safety check; or set like 200000000
jpeg_quality: 92             # when saving JPEG
